thorrak/tiltbridge

- .gitignore
- README.md
- data/settings.htm
- docs/source/global.rst
- platformio.ini
- src/http_server.cpp
- src/jsonConfigHandler.cpp
- src/sendData.cpp
- src/sendData.h
Cleanly add support for Brewfather pushing. I tested this; seems to work pretty well so far.
> Brewfather Support

- docs/source/hardware.rst
Updated the link for the ESP32 OLED Enclosure on Thingverse
> Updated ESP32 OLED Enclosure Link

- README.md
- data/settings.htm
- docs/source/User Guide/cloud_services.rst
- docs/source/global.rst
> Add support for BrewPi Remix

- docs/source/User Guide/cloud_services.rst
More for #13, also fixed what I think is a typo on top of the page.
> BrewPi Remix Support Part Deux

- data/calibration.htm
- data/index.htm
- data/settings.htm
- src/bridge_lcd.cpp
- src/http_server.cpp
- src/jsonConfigHandler.cpp
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
Implemented an option to switch between C and F in settings, updated the index.htm to use selected unit, updated the lcd display text to use selected unit.
I've also put in middle text for LCD_SSD1306, happy to remove that if it causes issues (seemed to have been explicitly not been implemented), but this work fine on my display.
> Temperature units

- data/settings.htm
- src/http_server.cpp
- src/sendData.cpp
MQTT Best Practices suggest that each device should be it's own subtopic.
Additionally, the Tiltpi JSON uses different attribute names and I think the should be the same for consistency
> Create MQTT subtopic to be inline with industry best practices

- data/index.htm
- data/settings.htm
- src/http_server.cpp
- src/tilt/tiltHydrometer.cpp
- src/wifi_setup.cpp
Update index.htm to display 4 decimals for sp gravity.
Update settings.htm tooltips to indicate allowable values for some
settings.
Update DNS/IP address validation and mDNS validation functions in
http_server.cpp & wifi_setup.cpp.
Fix comment in tiltHydrometer.cpp to match current implementation.
> Minor fixes and improvements.

- data/calibration.htm
- data/common.css
- data/help.htm
- data/index.htm
- data/index.js
- data/restarting.htm
- data/settings.htm
- data/updating.htm
- data/wifi_reset.htm
Added new format and coloring to Tilt cards:
> Color cards

- data/about.js
- data/settings.htm
- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/http_server.cpp
- src/http_server.h
- src/main.cpp
- src/tilt/tiltScanner.cpp
- src/wifi_setup.cpp
Notes from Tim's PM:
- Combined jquery requests of About.htm page into a single query.
- Seems to have a big impact on improving stability.
- The needed changes to the http_server were also part of this change.
- Replaced Arduino_GFX and Arduino_ILI9341 libraries with latest TFT_eSPI library.
- This library has much more efficient SPI access.
- Library recently added support for DMA access which reduces burden on the CPU during transfers to the screen hardware. This was enabled.
- The SetRotation() function does not work on the fly with this library and the code was changed to restart the tiltbridge if the invertTFT setting is changed
- TFT Touch functionality has been disabled for now. This should be possible to re-enable in the future.
- Moved the LCD screen handling work back to the …
> Ardjson tft

- data/settings.js
- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/http_server.cpp
- src/http_server.h
- src/main.cpp
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltScanner.cpp
- src/wifi_setup.cpp
Merging in @pletch's work to leverage a new [TFT library](https://github.com/Bodmer/TFT_eSPI).
We still have to find a way to dynamically reset the TFT display orientation, I've got a [question posted on the lib repo's discussion area](https://github.com/Bodmer/TFT_eSPI/discussions/931).
Other known issues/features to be addressed:
- HTML5 validation of config forms
- Update DHCP lease on hostname change
- "Factory reset" of controller
- Stability of TFT version
- ???
> New TFT Lib

- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltScanner.cpp
- src/tilt/tiltScanner.h
> Tiltscan update

- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
- src/tilt/tiltScanner.cpp
- src/tilt/tiltScanner.h
This addresses half of #91.  @LBussy can make the changes to best present on the home dashboard screen.  If possible, it might be nice to have this on the right side of the card header tile for each tilt.
> Add RSSI signal strength to Tilt json string

- data/index.htm
- data/index.js
> Add battery age to Index

- data/index.htm
- data/index.js
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
> Conditional html

- data/common.css
> Better colors for cards

- data/factoryreset.htm
- src/http_server.cpp
- src/http_server.h
- src/main.cpp
> Factory reset

- src/http_server.cpp
- src/main.cpp
- src/sendData.cpp
- src/sendData.h
> Mqtt radio crash

- data/settings.js
- src/http_server.cpp
- src/http_server.h
- src/main.cpp
- src/sendData.cpp
- src/wifi_setup.cpp
- src/wifi_setup.h
Closes #86 - allows a full reset (including DHCP) when hostname resets.
> Mdns reset

- data/common.css
- data/index.htm
- data/index.js
- data/restarting.js
- data/settings.js
- src/http_server.cpp
- src/http_server.h
- src/main.cpp
Fix Tilt tile header sizes so that the cards align even if there's no battery and/or Google Sheet entry.  Further, keep the text from wrapping and screwing that up as the tiles respond to screen resizing.
> Tile header

- platformio.ini
- src/OTAUpdate.cpp
> Client conflict

- platformio.ini
- src/OTAUpdate.h
- src/bridge_lcd.cpp
> Espi orientation

- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/main.cpp
- src/main.h
- src/sendData.cpp
- src/sendData.h
- src/serialhandler.cpp
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
- src/tilt/tiltScanner.cpp
- src/tilt/tiltScanner.h
- src/wifi_setup.cpp
Closes #140.  This branch handles the rest of the performance issues, although we still have the WFT issues when hammering the about page.
> Async work

- data/about.js
> Re-nice the about page

- LICENSE
- data/calibration.htm
- data/settings.htm
- docs/source/User Guide/cloud_services.rst
- docs/source/User Guide/initial_setup.rst
- docs/source/User Guide/updates_and_wifi_reset.rst
- docs/source/about.rst
- docs/source/changelog.rst
- docs/source/development.rst
- docs/source/installation.rst
- platformio.ini
- src/OTAUpdate.cpp
- src/OTAUpdate.h
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/http_server.cpp
- src/http_server.h
- src/jsonconfig.cpp
- src/jsonconfig.h
- src/main.cpp
- src/resetreasons.h
- src/version.cpp
- src/version.h
- src/watchButtons.cpp
- src/watchButtons.h
- src/wifi_setup.cpp
- src/wifi_setup.h
Includes a couple of things in preparation for v1.0.0 release:
- Cleans up (combines) google sheets config calls
- Updates documentation
- Triggers calls to each push target as the "key configuration setting" is updated (e.g. Brewers Friend API key, local targetURL, etc.)
- Sets static versions for libraries (where possible)
- Other minor cleanup
> Gsheets config cleanup

- platformio.ini
- src/sendData.cpp
- src/sendData.h
Incorporated ideas from @pletch via @thorrak.
> Wifi client work

- platformio.ini
- src/wifi_setup.cpp
Closes #158, also handles the DHCP name issue (albeit in a not very glamorous way).
> Fix DHCP name chane and bandwith on portal

- docs/source/changelog.rst
- platformio.ini
- src/bridge_lcd.cpp
- src/jsonconfig.cpp
- src/jsonconfig.h
- src/main.cpp
- src/sendData.cpp
- src/sendData.h
- src/tilt/tiltScanner.cpp
**Amongst other things:**
- Fix issue that can cause Google Sheets posts to periodically fail
- Corrected delay timers for Google Sheets, Brewer's Friend, and BrewFather (Seconds != Milliseconds)
- Other behind-the-scenes cleanup
> Google Sheets Revamp

- src/main.cpp
- src/wifi_setup.cpp
This will do two things:
1. If the WiFi disconnects and cannot reconnect, it will reboot the ESP device
2. It will reboot every 24 hours since the core and BLE libs are still not playing nice together
> Wifi reboot

- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
> Move to ThingPulse lib

- docs/source/development.rst
- docs/source/global.rst
Adding a few very light notes on using `pio`.
> docs: add development notes

- platformio.ini
> TOUCH_CS assignment to val of 1 borks Serial monitoring

- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/http_server.cpp
- src/http_server.h
- src/main.cpp
- src/main.h
- src/parseTarget.cpp
- src/parseTarget.h
- src/sendData.cpp
- src/sendData.h
> Merge refactoring

- platformio.ini
- src/sendData.cpp
- src/sendData.h
This updates the MQTT library to the latest version, and rewrites the MQTT sender to reduce potential points of error. Although this may not fix #247, it is a start.
> Rewrite MQTT Sender

- src/sendData.cpp
- Fixes a bug where setting an MQTT broker will crash the TiltBridge
- Properly triggers a disconnect from the MQTT broker when the broker host is unset
- Adds connection checking to the MQTT loop
> Fix MQTT (Re)initialization

- .github/workflows/build.yml
- docs/source/hardware.rst
- src/bridge_lcd.cpp
- src/sendData.cpp
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
- src/tilt/tiltScanner.cpp
Brings 'next' up to date with the MQTT (and other data sender) fixes/enhancements currently in `devel`.
> Keep Next up to date
