thorrak/tiltbridge

- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
I was surprised to see outdated information on the TiltBridge because it was too far away from my fermenter to receive the BLE message. So, expire the data after 5 minutes. 
Tested on hardware with a tilt in range and out of range (ie: off)
> Expire data after 5 minutes of not getting the BLE broadcast

- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/wifi_setup.cpp
This pull request adds display support for the https://github.com/Xinyuan-LilyGO/TTGO-T-Display board using the https://github.com/Bodmer/TFT_eSPI library.
I also fixed a typo in wifi_setup.cpp that is triggered only when debugging print statements are turned on:
```
src/wifi_setup.cpp:208:28: error: lvalue required as left operand of assignment
if(WLcount % 5 = 0)
^
```
> Add support for the TTGO T-Display board using TFT_eSPI

- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
- src/wifi_setup.cpp
This implements color text for each tilt. This is useful for the TTGO T-Display, which doesn't have enough screen width to show Color, Temp, and Gravity. We use the font color to display the tilt name, and then use the two columns displayed for Temp and Gravity.
This pull request contains additional patches on top of https://github.com/thorrak/tiltbridge/pull/25 which should be merged first.
> Add color text for each tilt

- data/settings.htm
- src/SecureWithRedirects.cpp
- src/SecureWithRedirects.h
- src/http_server.cpp
- src/jsonConfigHandler.cpp
- src/sendData.cpp
- src/sendData.h
Implement the ability to push to https://brewstat.us/
BrewStatus uses `application/x-www-form-urlencoded` but the `send_to_url()` function was hard wired to use `application/json` so I added an argument to allow the user to set the content type in the headers.
> Implement pushing to BrewStatus

- src/tilt/tiltScanner.cpp
These changes modify the load_tilt_from_advert_hex function to 
eliminate use of NimBLEUtils::buildHexData.
As an alternative, the advert_hex_string is directly iterated to
place the color,temperature, and sp gravity data into char arrays.
These changes appear to reduce heap thrashing when monitored via
debugging output from esp_get_free_heap_size().
> Modify parsing of load_tilt_from_advert_hex function

- src/sendData.cpp
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
Update to correctly set temperature unit designation in the MQTT payload.
> Set temp unit correctly in MQTT Payload

- data/settings.htm
- src/http_server.cpp
- src/jsonConfigHandler.cpp
- src/sendData.cpp
- src/wifi_setup.cpp
It bothered me that the settings page just returns silently if an invalid setting is input.  I added some code to append an all_valid flag to the end of the json string when it is requested by the http client.  This way, the javascript can pop up an alert box if one of the settings was found to be invalid by the process_config function.  There is probably a better way to do this but this is the first approach I could come up with without more research into options.
> Provide alert box if setting is invalid, set DHCP name correctly, add general timezone offset for use with google sheets.

- src/http_server.cpp
- src/tilt/tiltHydrometer.cpp
Valid timezone offsets from GMT range from -12 to +14.
See https://www.joda.org/joda-time/timezones.html
> Valid tz offset is -12 to +14.

- src/tilt/tiltHydrometer.cpp
This change should handle the edge case where a user switches in a Pro for a non-Pro of the same color without first letting the existing Tilt expire.  This is related to issue #51 just added.
> Handle unexpired swap from Pro to non-Pro

- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
Now that I have capability to emulate one or more tilts and can dynamically switch between the original Tilt and the Tilt Pro, an error in the smoothing implementation became apparent.  Also increased scaling factor of the smoothing calculations to 1000 since there is plenty of headroom in uint32_t to do so.
> Identified another issue in smoothing implementation

- src/main.cpp
I neglected to include instruction to reset status of config_updated when I moved it to the main loop.  This should be incorporated quickly becuase it is likely writing to spiffs repeatedly in the main loop after config is updated.  OOPS!!!
> Urgent fix to ensure config_updated status is reset

- platformio.ini
I believe this setting polluted the platformio.ini during one of my commits.  
One of the ESP32 boards I was using would always reboot when attaching monitor and this was an attempt to eliminate.  However, I have actually tracked down some instability with serial connection & debugging to using a setting of 1. I am now using 0 as a default.  Not sure if others have had any weird issues related to this??
> Monitor_dtr = 1 causing instability with Serial

- src/http_server.cpp
- src/sendData.cpp
- src/tilt/tiltScanner.cpp
I think we should proportion a little more time to the Wifi radio so the Window and Interval were adjusted.  I selected prime numbers for both to hopefully reduce risk of developing a beat frequency between the advertising interval of a Tilt and the scan interval time.  Please test and let me know if the settings create any issues with actually discovering and receiving regular updates from a physical Tilt device.  I have been using my emulator with two different ESP32 devices each using a 750 ms sleep and a 50 ms duration for which advertising is on.  I am unsure what the actual Tilt uses but Thorrak mentioned the Tilts send out advertisements about every 800 ms.
> Adjust BLE scan window and interval

- src/http_server.cpp
Now that we have moved larger config items to heap, use stack for the smaller json object generation.
> Use stack for about json responses

- src/tilt/tiltScanner.cpp
- src/tilt/tiltScanner.h
Nimble provides a library boolean which indicates if a scan is in
progress eliminating the need for m_scan_active flag.
The race condition issue mentioned in code comments has also been
addressed through recent Nimble commits removing need to explicitly
stop scan.
Simplified the code and removed the callback function that is not
currently used other than to set the removed m_scan_active flag.
> Simplify tiltScanner::scan.

- src/bridge_lcd.cpp
Related to #57 and #103, the header needed to be updated for the new logo.
> Change log/header for eSPI

- src/bridge_lcd.cpp
Black Tilt corresponds to white text and shows a white rectangle on the TFT screen. This change adjusts the color of the rectangle to be a very dark grey which still shows some contrast.
> Change Black Tilt white box to drk grey on TFT

- Json Models/Tilt JSON.md
- src/http_server.cpp
- src/sendData.cpp
- src/tilt/tiltHydrometer.h
- src/tilt/tiltScanner.cpp
The char buffer in the calling functions to tilt_to_json_string should be scaled against the condensed json string size rather than json object size.
> Set char buffer sizes to json string length

- src/sendData.cpp
This fixes an oversight (reported in #180) where the http pushes were always to port 80.
> Nonstd port

- data/settings.js
- src/sendData.cpp
- src/sendData.h
- Add new generic http function for sending json with the standard Httpclient library: Grainfather HTTP response is ``HTTP/2 201``. That does not work with ``strcmp(status +9, "200 OK")`` in ``dataSendHandler::send_to_url``. So I have added a new ``dataSendHandler::http_send_json`` function that uses the  Arduino Httpclient library as it ``dataSendHandler::send_to_google`` already does.
- Fix javascript code for Grainfather settings
- Set the send_lock flag inside the check block: Otherwise it gets overwritten at the end of the function and the next run could cause problems
> Improved Grainfather Support

- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
Add support for M5Stick-C display.
Pin espressif/arduino-esp32 version for now, it seems like the arduino core for the ESP32 has been recently updated on github and is now incompatible with our libraries, pin it to before the update for now.
> Support M5StickC display

- .github/workflows/build.yml
Action is based on reference implementation:
https://docs.platformio.org/en/latest/integration/ci/github-actions.html
The only local change of significance in the action is that we've disabled the
platformio asset caching step, given that we currently have some un-pinned
dependencies. See discussion in https://github.com/thorrak/tiltbridge/pull/185
> Add Github actions workflow to build on PR/push.

- docs/source/User Guide/cloud_services.rst
Document how Home Assistant users should:
* Flash TiltBridge onto an ESP32
* Configure TileBridge to publish via MQTT
* configure Home Assistant to receive TiltBridge data
> Document Home Assistant howto details

- .github/workflows/build.yml
- data/settings.htm
- data/settings.js
- docs/source/changelog.rst
- platformio.ini
- src/bridge_lcd.cpp
- src/bridge_lcd.h
- src/http_server.cpp
- src/http_server.h
- src/jsonconfig.cpp
- src/jsonconfig.h
- src/sendData.cpp
- src/sendData.h
This PR refactors the LCD code, consolidating the "D32 TFT" and "ESPI TFT" code. This also substantially refactors the "M5" target to utilize (largely) the same code as the "ESPI TFT" target.
Additionally, this PR adds a new "custom user target" which sends the same JSON message as is sent to Brewfather and Brewer's Friend as requested by a HBT user. This functionality is currently untested.
> Refactor LCD code and add "Custom User Target"

- src/bridge_lcd.cpp
Fix #228 for Lolin D32 Pro & Lolin TFT combination.
> Fix Logo Color on TFT

- platformio.ini
- src/JsonKeys.h
- src/http_server.cpp
- src/http_server.h
- src/http_server_generic.cpp
- src/main.cpp
- src/sendData.cpp
- src/tilt/tiltScanner.cpp
- src/tilt/tiltScanner.h
The asynchronous HTTP server has had many issues in the past, and isn't really necessary. This reverts to the standard, synchronous HTTP Server.
> Switch to synchronous HTTP server

- src/sendData.cpp
- src/sendData.h
This tags the uptime as being an "additional attribute" (thereby preventing the same reading being sent repeatedly from updating the 'last changed' timestamp), and adds additional device configuration information to the announcement. 
Closes #248
> Add additional information to the Home Assistant MQTT Auto Discovery messages

- .github/workflows/build.yml
- src/bridge_lcd.cpp
- src/sendData.cpp
- src/tilt/tiltHydrometer.cpp
- src/tilt/tiltHydrometer.h
- src/tilt/tiltScanner.cpp
This PR does a number of things:
- Gets rid of as many std::strings as possible (freeing up flash space)
- Fixes a bug that would cause sends to taplist.io to send the wrong temperature units
- Prevent attempts to connect to MQTT when no WiFi is present
- Fixes a bug where setting an MQTT broker would crash the TiltBridge
- Clean up MQTT reinitialization
> Clean up MQTT and other tweaks/bugfixes
